//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_asignacion_de_proyectos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sistema_de_asignacion_de_proyectos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha agregado al usuario como colaborador.
        /// </summary>
        internal static string AgregarExitoso {
            get {
                return ResourceManager.GetString("AgregarExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Usuario.
        /// </summary>
        internal static string AgregarUsuario {
            get {
                return ResourceManager.GetString("AgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han agregado los usuarios como colaboradores.
        /// </summary>
        internal static string AgregarUsuariosExitoso {
            get {
                return ResourceManager.GetString("AgregarUsuariosExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analistas.
        /// </summary>
        internal static string Analistas {
            get {
                return ResourceManager.GetString("Analistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este cambio es irreversible.
        /// </summary>
        internal static string AvisoCambio {
            get {
                return ResourceManager.GetString("AvisoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido eliminar al usuario debido a que es el ultimo analista asignado en un proyecto activo.
        /// </summary>
        internal static string AvisoUltimoAnalista {
            get {
                return ResourceManager.GetString("AvisoUltimoAnalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario participa de proyectos activos.
        /// </summary>
        internal static string AvisoUProyectosActivos {
            get {
                return ResourceManager.GetString("AvisoUProyectosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        internal static string btnAccederLogin {
            get {
                return ResourceManager.GetString("btnAccederLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        internal static string btnAddDepartamento {
            get {
                return ResourceManager.GetString("btnAddDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        internal static string btnAddEmpleado {
            get {
                return ResourceManager.GetString("btnAddEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        internal static string btnAddEquipo {
            get {
                return ResourceManager.GetString("btnAddEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Colaboradores.
        /// </summary>
        internal static string btnAgregarUsuario {
            get {
                return ResourceManager.GetString("btnAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Idioma.
        /// </summary>
        internal static string btnCambiarIdioma {
            get {
                return ResourceManager.GetString("btnCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Proyecto.
        /// </summary>
        internal static string btnCrearProyectos {
            get {
                return ResourceManager.GetString("btnCrearProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string BtnDesplegableAgregar {
            get {
                return ResourceManager.GetString("BtnDesplegableAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Notificacion.
        /// </summary>
        internal static string btnEliminarNotis {
            get {
                return ResourceManager.GetString("btnEliminarNotis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarProyectos {
            get {
                return ResourceManager.GetString("btnEliminarProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Colaboradores.
        /// </summary>
        internal static string btnEliminarUsuarios {
            get {
                return ResourceManager.GetString("btnEliminarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string btnExportar {
            get {
                return ResourceManager.GetString("btnExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string btnFiltrar {
            get {
                return ResourceManager.GetString("btnFiltrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar Proyectos.
        /// </summary>
        internal static string btnGestionarProyectos {
            get {
                return ResourceManager.GetString("btnGestionarProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis proyectos.
        /// </summary>
        internal static string btnMisProyectos {
            get {
                return ResourceManager.GetString("btnMisProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Caracteristicas.
        /// </summary>
        internal static string btnModificarCaract {
            get {
                return ResourceManager.GetString("btnModificarCaract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModificarProyectos {
            get {
                return ResourceManager.GetString("btnModificarProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        internal static string btnPagos {
            get {
                return ResourceManager.GetString("btnPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string btnProyectos {
            get {
                return ResourceManager.GetString("btnProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string btnSeleccionarRol {
            get {
                return ResourceManager.GetString("btnSeleccionarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Tareas.
        /// </summary>
        internal static string btnTareas {
            get {
                return ResourceManager.GetString("btnTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string CambiarContraseña {
            get {
                return ResourceManager.GetString("CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de contraseña.
        /// </summary>
        internal static string CambioContra {
            get {
                return ResourceManager.GetString("CambioContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada correctamente.
        /// </summary>
        internal static string CambioContraExitoso {
            get {
                return ResourceManager.GetString("CambioContraExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Solicitante.
        /// </summary>
        internal static string ClienteSolicitante {
            get {
                return ResourceManager.GetString("ClienteSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completar todos los campos.
        /// </summary>
        internal static string CompletarDatos {
            get {
                return ResourceManager.GetString("CompletarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de cerrar la sesión?.
        /// </summary>
        internal static string ConfirmarCierreSesion {
            get {
                return ResourceManager.GetString("ConfirmarCierreSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea Continuar?.
        /// </summary>
        internal static string ConfirmarContinuacion {
            get {
                return ResourceManager.GetString("ConfirmarContinuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de querer eliminar a este usuario?.
        /// </summary>
        internal static string ConfirmarEliminacionU {
            get {
                return ResourceManager.GetString("ConfirmarEliminacionU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si continúa, abandonará la sesión.
        /// </summary>
        internal static string ContinuarCierreSesion {
            get {
                return ResourceManager.GetString("ContinuarCierreSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        internal static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        internal static string Correo_Electronico {
            get {
                return ResourceManager.GetString("Correo Electronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo.
        /// </summary>
        internal static string Costo {
            get {
                return ResourceManager.GetString("Costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrolladores.
        /// </summary>
        internal static string Desarrolladores {
            get {
                return ResourceManager.GetString("Desarrolladores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicita servicios y revisa el estado de sus proyecto.
        /// </summary>
        internal static string DescCliente {
            get {
                return ResourceManager.GetString("DescCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiona tareas, carga reportes y sigue el avance.
        /// </summary>
        internal static string DescEmpleado {
            get {
                return ResourceManager.GetString("DescEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseña proyectos y coordina equipos técnicos.
        /// </summary>
        internal static string DescIngeniero {
            get {
                return ResourceManager.GetString("DescIngeniero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado correctamente el usuario seleccionado.
        /// </summary>
        internal static string EliminarCorrecto {
            get {
                return ResourceManager.GetString("EliminarCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario Seleccionado.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han eliminado correctamente los usuarios seleccionados.
        /// </summary>
        internal static string EliminarVariosCorrecto {
            get {
                return ResourceManager.GetString("EliminarVariosCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario.
        /// </summary>
        internal static string ElUsuario {
            get {
                return ResourceManager.GetString("ElUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        internal static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambiar la contraseña de otro administrador.
        /// </summary>
        internal static string ErrorContraAdmin {
            get {
                return ResourceManager.GetString("ErrorContraAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este Correo ya se encuentra registrado.
        /// </summary>
        internal static string ErrorCorreoRegistrado {
            get {
                return ResourceManager.GetString("ErrorCorreoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI inválido.
        /// </summary>
        internal static string ErrorDni {
            get {
                return ResourceManager.GetString("ErrorDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI o el Correo electronico ya estan registrados.
        /// </summary>
        internal static string ErrorDniCorreo {
            get {
                return ResourceManager.GetString("ErrorDniCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de entrada no es válido. Verificá los datos ingresados.
        /// </summary>
        internal static string ErrorFormato {
            get {
                return ResourceManager.GetString("ErrorFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posees los permisos para eliminar a este usuario.
        /// </summary>
        internal static string ErrorPermisos {
            get {
                return ResourceManager.GetString("ErrorPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un rol valido.
        /// </summary>
        internal static string ErrorRol {
            get {
                return ResourceManager.GetString("ErrorRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una notificación para marcar como leída.
        /// </summary>
        internal static string ErrorSeleccionNotificacion {
            get {
                return ResourceManager.GetString("ErrorSeleccionNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un usuario.
        /// </summary>
        internal static string ErrorSeleccionUsuario {
            get {
                return ResourceManager.GetString("ErrorSeleccionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de usuario no soportado.
        /// </summary>
        internal static string ErrorTipoUsuario {
            get {
                return ResourceManager.GetString("ErrorTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a incluyendo al menos un analista y un solicitante..
        /// </summary>
        internal static string FaltaAnalistaSolicitante {
            get {
                return ResourceManager.GetString("FaltaAnalistaSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Suscripcion.
        /// </summary>
        internal static string FechaSuscripcion {
            get {
                return ResourceManager.GetString("FechaSuscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fue Creado.
        /// </summary>
        internal static string FueCreado {
            get {
                return ResourceManager.GetString("FueCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuiste asignado al proyecto.
        /// </summary>
        internal static string FuisteAsignado {
            get {
                return ResourceManager.GetString("FuisteAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cliente {
            get {
                object obj = ResourceManager.GetObject("icon_cliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_empleado {
            get {
                object obj = ResourceManager.GetObject("icon_empleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_ingeniero {
            get {
                object obj = ResourceManager.GetObject("icon_ingeniero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_ingeniero2 {
            get {
                object obj = ResourceManager.GetObject("icon_ingeniero2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id del Proyecto.
        /// </summary>
        internal static string IdProyecto {
            get {
                return ResourceManager.GetString("IdProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingeniero.
        /// </summary>
        internal static string Ingeniero {
            get {
                return ResourceManager.GetString("Ingeniero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una nueva contraseña.
        /// </summary>
        internal static string IngresarContra {
            get {
                return ResourceManager.GetString("IngresarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inicio_sesion {
            get {
                object obj = ResourceManager.GetObject("inicio sesion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        internal static string lblDesde {
            get {
                return ResourceManager.GetString("lblDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Apellido.
        /// </summary>
        internal static string lblNombreApellido {
            get {
                return ResourceManager.GetString("lblNombreApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        internal static string Lenguaje {
            get {
                return ResourceManager.GetString("Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tiene cuenta? Registrarse.
        /// </summary>
        internal static string linkLabel1 {
            get {
                return ResourceManager.GetString("linkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log_out_2355227_1920 {
            get {
                object obj = ResourceManager.GetObject("log-out-2355227_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize_5907715_1920 {
            get {
                object obj = ResourceManager.GetObject("maximize-5907715_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize_5907714_1920 {
            get {
                object obj = ResourceManager.GetObject("minimize_5907714_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        internal static string MiPerfil {
            get {
                return ResourceManager.GetString("MiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Usuario Seleccionado.
        /// </summary>
        internal static string ModificarUsuario {
            get {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Proyecto.
        /// </summary>
        internal static string NombreProyecto {
            get {
                return ResourceManager.GetString("NombreProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Notificaciones.
        /// </summary>
        internal static string NoNotificaciones {
            get {
                return ResourceManager.GetString("NoNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser eliminado.
        /// </summary>
        internal static string NoPuedeEliminar {
            get {
                return ResourceManager.GetString("NoPuedeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes usuarios no han sido eliminados debido a que no posees los permisos necesarios.
        /// </summary>
        internal static string NotificarUsuariosNoEliminados {
            get {
                return ResourceManager.GetString("NotificarUsuariosNoEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea registrarse?.
        /// </summary>
        internal static string OfrecerRegistro {
            get {
                return ResourceManager.GetString("OfrecerRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plataforma.
        /// </summary>
        internal static string Plataforma {
            get {
                return ResourceManager.GetString("Plataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__1_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posible Fecha de Entrega.
        /// </summary>
        internal static string PosibleFechaEntrega {
            get {
                return ResourceManager.GetString("PosibleFechaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string Proyecto {
            get {
                return ResourceManager.GetString("Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto creado exitosamente.
        /// </summary>
        internal static string ProyectoCreado {
            get {
                return ResourceManager.GetString("ProyectoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrado Exitosamente.
        /// </summary>
        internal static string RegistroExitoso {
            get {
                return ResourceManager.GetString("RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea asignada exitosamente.
        /// </summary>
        internal static string TareaAsignada {
            get {
                return ResourceManager.GetString("TareaAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea Asignada.
        /// </summary>
        internal static string TareaAsignadaTexto {
            get {
                return ResourceManager.GetString("TareaAsignadaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Proyecto.
        /// </summary>
        internal static string TuProyecto {
            get {
                return ResourceManager.GetString("TuProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es el ultimo analista asignado al proyecto.
        /// </summary>
        internal static string UltimoAnalista {
            get {
                return ResourceManager.GetString("UltimoAnalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserIcon {
            get {
                object obj = ResourceManager.GetObject("UserIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no se encuentra registrado.
        /// </summary>
        internal static string UsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNoEncontrado", resourceCulture);
            }
        }
    }
}
